-- Seed data for warehouse_types table
INSERT INTO public.warehouse_types (
    type_code,
    type_name,
    description,
    icon_name,
    default_temperature,
    temp_range_min,
    temp_range_max,
    default_humidity,
    humidity_range_min,
    humidity_range_max,
    air_change_rate,
    recommended_velocity,
    display_order,
    is_active
) VALUES 
(
    'cold_storage',
    'Soğuk Muhafaza',
    'Gıda ürünlerinin taze kalması için ideal soğuk depolama',
    'fa-snowflake',
    4.0,
    0.0,
    4.0,
    90.0,
    85.0,
    95.0,
    6.0,
    0.25,
    1,
    true
),
(
    'frozen_storage',
    'Dondurulmuş Depo',
    'Dondurulmuş ürünlerin uzun süreli saklanması için',
    'fa-icicles',
    -18.0,
    -25.0,
    -18.0,
    85.0,
    80.0,
    90.0,
    4.0,
    0.20,
    2,
    true
),
(
    'blast_freezing',
    'Şok Dondurma',
    'Ürünlerin hızlı dondurulması için yüksek performanslı sistem',
    'fa-wind',
    -35.0,
    -40.0,
    -30.0,
    NULL,
    NULL,
    NULL,
    10.0,
    3.0,
    3,
    true
),
(
    'pre_cooling',
    'Ön Soğutma',
    'Ürünlerin ana depolamaya geçmeden önce soğutulması',
    'fa-temperature-low',
    6.0,
    2.0,
    8.0,
    90.0,
    85.0,
    95.0,
    8.0,
    0.50,
    4,
    true
),
(
    'controlled_atmosphere',
    'Kontrollü Atmosfer',
    'Özel gaz karışımı ve nem kontrolü ile uzun süreli saklama',
    'fa-cloud',
    0.0,
    -2.0,
    2.0,
    92.0,
    90.0,
    95.0,
    2.0,
    0.15,
    5,
    true
),
(
    'medical_storage',
    'İlaç/Medikal',
    'İlaç ve medikal ürünlerin güvenli saklanması için',
    'fa-prescription-bottle-alt',
    4.0,
    2.0,
    8.0,
    40.0,
    30.0,
    50.0,
    4.0,
    0.20,
    6,
    true
);